default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

newdev:
  <<: *default
  username: ios_demo
  password: ios_demo
  database: ios_demo
  host: localhost

development:
  <<: *default
  database: ios_demo_development

test:
  <<: *default
  database: ios_demo_test

docker:
  <<: *default
  database: ios_demo_docker
  username: postgres
  host: <%= ENV['IOSDEMO_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['IOSDEMO_DB_1_PORT_5432_TCP_PORT'] %>

